/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staycationprojectreplacing.src.staycationproject;

 import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

 
public class AdminUserManagement extends javax.swing.JFrame {
private Connection cn;
private PreparedStatement pst;
private ResultSet rs;

    
  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminUserManagement.class.getName());

    /**
     * Creates new form AdminUserManagement
     */
    public AdminUserManagement() { 
        initComponents();
        try {
    cn = DriverManager.getConnection("jdbc:mysql://localhost/staycation","root","");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Database connection failed: " + ex.getMessage());
}

      admintable.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {}, // empty rows
    new String [] { "User ID", "Name", "Email", "Phone", "User Type" } // column headers
) {
    Class[] types = new Class [] {
        Integer.class, String.class, String.class, String.class, String.class
    };
    @Override
    public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
    }
});
          getContentPane().add(jPanel1);
          jPanel1.setBounds(10, 10, 827, 500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        passwordfield = new javax.swing.JPasswordField();
        addbutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        admintable = new javax.swing.JTable();
        firstrecord = new javax.swing.JButton();
        lastrecord = new javax.swing.JButton();
        nextrecord = new javax.swing.JButton();
        previousrecord = new javax.swing.JButton();
        displayallrecords = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Admin User Management");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 280, 23);

        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 61, 31, 16);

        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 109, 28, 16);

        jLabel4.setText("Phone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(16, 162, 33, 16);

        jLabel5.setText("User_type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(16, 216, 60, 16);

        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(16, 260, 70, 16);

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        jPanel1.add(namefield);
        namefield.setBounds(226, 55, 91, 22);

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailfield);
        emailfield.setBounds(226, 106, 91, 22);

        phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefieldActionPerformed(evt);
            }
        });
        jPanel1.add(phonefield);
        phonefield.setBounds(226, 159, 91, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customers", "Staff" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(226, 210, 91, 22);

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordfield);
        passwordfield.setBounds(226, 257, 91, 22);

        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton);
        addbutton.setBounds(16, 310, 72, 23);

        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton);
        updatebutton.setBounds(139, 310, 72, 23);

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton);
        deletebutton.setBounds(246, 310, 72, 23);

        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton);
        searchbutton.setBounds(16, 361, 72, 23);

        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(clearbutton);
        clearbutton.setBounds(139, 361, 72, 23);

        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton);
        exitbutton.setBounds(246, 361, 72, 23);

        admintable.setBackground(new java.awt.Color(204, 204, 204));
        admintable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "Name", "Email", "Phone", "User_Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(admintable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 0, 463, 378);

        firstrecord.setText("First Record");
        firstrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstrecordActionPerformed(evt);
            }
        });
        jPanel1.add(firstrecord);
        firstrecord.setBounds(333, 396, 100, 23);

        lastrecord.setText("Last Record");
        lastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastrecordActionPerformed(evt);
            }
        });
        jPanel1.add(lastrecord);
        lastrecord.setBounds(455, 396, 91, 23);

        nextrecord.setText("Next Record");
        nextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextrecordActionPerformed(evt);
            }
        });
        jPanel1.add(nextrecord);
        nextrecord.setBounds(582, 396, 95, 23);

        previousrecord.setText("Previous Record");
        previousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousrecordActionPerformed(evt);
            }
        });
        jPanel1.add(previousrecord);
        previousrecord.setBounds(695, 396, 115, 23);

        displayallrecords.setText("Display All");
        displayallrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayallrecordsActionPerformed(evt);
            }
        });
        jPanel1.add(displayallrecords);
        displayallrecords.setBounds(512, 437, 85, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 827, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrecordActionPerformed
        // TODO add your handling code here:
        getfirstrecord();
    }//GEN-LAST:event_firstrecordActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        getdeleterecords();
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        getupdate();
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        getaddbutton();
    }//GEN-LAST:event_addbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        getsearch();
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        getclear();
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void lastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastrecordActionPerformed
        // TODO add your handling code here:
        getlastrecord();
    }//GEN-LAST:event_lastrecordActionPerformed

    private void nextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextrecordActionPerformed
        // TODO add your handling code here:
        getnextrecord();
    }//GEN-LAST:event_nextrecordActionPerformed

    private void previousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousrecordActionPerformed
        // TODO add your handling code here:
        getpreviousrecord();
    }//GEN-LAST:event_previousrecordActionPerformed

    private void displayallrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayallrecordsActionPerformed
        // TODO add your handling code here:
        getdisplayrecords();
    }//GEN-LAST:event_displayallrecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminUserManagement().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTable admintable;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton displayallrecords;
    private javax.swing.JTextField emailfield;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton firstrecord;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastrecord;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton nextrecord;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton previousrecord;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables

   
        private void getaddbutton() {
    try {
        String nameVal = namefield.getText().trim();
        String emailVal = emailfield.getText().trim();
        String phoneVal = phonefield.getText().trim();
        String userTypeVal = (String) jComboBox1.getSelectedItem();
        String passwordVal = String.valueOf(passwordfield.getPassword());

        if(nameVal.isEmpty() || emailVal.isEmpty() || phoneVal.isEmpty() || passwordVal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
            return;
        }

        pst = cn.prepareStatement("INSERT INTO login ( name, email, phone, user_type, password) VALUES (?, ?, ?, ?, ?)");
        pst.setString(1, nameVal);
        pst.setString(2, emailVal);
        pst.setString(3, phoneVal);
        pst.setString(4, userTypeVal);
        pst.setString(5, passwordVal);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "User added successfully!");
        getdisplayrecords(); // refresh table

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error adding user: " + ex.getMessage());
    }
}

    

    private void getdeleterecords() {
        try {
        int selectedRow = admintable.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a row to delete");
            return;
        }
        int id = (Integer) admintable.getValueAt(selectedRow, 0);
        pst = cn.prepareStatement("DELETE FROM login WHERE user_id=?");
        pst.setInt(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "User deleted successfully!");
        getdisplayrecords();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error deleting user: " + ex.getMessage());
    }
}
   

    private void getupdate() {
    try {
        int selectedRow = admintable.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Select a row to update");
            return;
        }

        int id = (Integer) admintable.getValueAt(selectedRow, 0);
        String nameVal = namefield.getText().trim();
        String emailVal = emailfield.getText().trim();
        String phoneVal = phonefield.getText().trim();
        String userTypeVal = (String) jComboBox1.getSelectedItem();
        String passwordVal = String.valueOf(passwordfield.getPassword());

       pst = cn.prepareStatement(
    "UPDATE users SET name=?, email=?, phone=?, user_type=? WHERE user_id=?");
    pst.setString(1, nameVal);
    pst.setString(2, emailVal);
    pst.setString(3, phoneVal);
    pst.setString(4, userTypeVal);
    pst.setInt(5, id);
    pst.executeUpdate();


        JOptionPane.showMessageDialog(null, "User updated successfully!");
        getdisplayrecords();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error updating the user: " + ex.getMessage());
    }


    }

    private void getsearch() {
        try {
        String searchName = namefield.getText().trim();
        DefaultTableModel model = (DefaultTableModel) admintable.getModel();
        model.setRowCount(0);

        pst = cn.prepareStatement("SELECT * FROM login WHERE name LIKE ?");
        pst.setString(1, "%" + searchName + "%");
        rs = pst.executeQuery();

        while(rs.next()) {
            Object[] row = {
                rs.getInt("user_id"),
                rs.getString("name"),
                rs.getString("email"),
                rs.getString("phone"),
                rs.getString("user_type")
            };
            model.addRow(row);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error searching user: " + ex.getMessage());
    }
}
   

private void getclear() {
    namefield.setText("");
    emailfield.setText("");
    phonefield.setText("");
    passwordfield.setText("");
    jComboBox1.setSelectedIndex(0);
}
    

private void getfirstrecord() {
    if(admintable.getRowCount() > 0)
        admintable.setRowSelectionInterval(0, 0);
}
    

private void getlastrecord() {
    int last = admintable.getRowCount() - 1;
    if(last >= 0) admintable.setRowSelectionInterval(last, last);
}
    

    private void getnextrecord() {
    int selectedRow = admintable.getSelectedRow();
    if(selectedRow < admintable.getRowCount() - 1)
        admintable.setRowSelectionInterval(selectedRow + 1, selectedRow + 1);
}
    

    private void getpreviousrecord() {
    int selectedRow = admintable.getSelectedRow();
    if(selectedRow > 0)
        admintable.setRowSelectionInterval(selectedRow - 1, selectedRow - 1);
}
    

        private void getdisplayrecords() {
    try {
        DefaultTableModel model = (DefaultTableModel) admintable.getModel();
        model.setRowCount(0); // clear table

        pst = cn.prepareStatement("SELECT * FROM users");
rs = pst.executeQuery();
while(rs.next()) {
    Object[] row = {
        rs.getInt("user_id"),
        rs.getString("name"),
        rs.getString("email"),
        rs.getString("phone"),
        rs.getString("user_type")
    };
    model.addRow(row);
}
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error displaying the records: " + ex.getMessage());
    }
}
}
