package staycation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class HotelStaffBooking extends javax.swing.JFrame {
    Connection cn;
    PreparedStatement pst;
    ResultSet rs;
    public HotelStaffBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingtable = new javax.swing.JTable();
        hotelstaffbooking = new javax.swing.JLabel();
        checkinbtn = new javax.swing.JButton();
        checkoutbtn = new javax.swing.JButton();
        loadtabledetails = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bookingtable.setBackground(new java.awt.Color(204, 204, 204));
        bookingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Registration Id ", "Name", "Room Type", "Check In Date", "Check Out Date", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 690, 270);

        hotelstaffbooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hotelstaffbooking.setText("CheckIn's and Out Staff Booking");
        getContentPane().add(hotelstaffbooking);
        hotelstaffbooking.setBounds(250, 10, 320, 25);

        checkinbtn.setText("Check In");
        checkinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinbtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkinbtn);
        checkinbtn.setBounds(20, 330, 76, 23);

        checkoutbtn.setText("Check Out");
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutbtn);
        checkoutbtn.setBounds(470, 330, 86, 23);

        loadtabledetails.setText("Load  Bookings");
        loadtabledetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadtabledetailsActionPerformed(evt);
            }
        });
        getContentPane().add(loadtabledetails);
        loadtabledetails.setBounds(240, 330, 120, 23);

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn);
        exitbtn.setBounds(260, 380, 72, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vicodec\\Downloads\\download (3).jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -130, 960, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinbtnActionPerformed
        // TODO add your handling code here:
        checkin();
    }//GEN-LAST:event_checkinbtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // TODO add your handling code here:
        checkout();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void loadtabledetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadtabledetailsActionPerformed
        // TODO add your handling code here:
        loadbookings();
    }//GEN-LAST:event_loadtabledetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelStaffBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelStaffBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelStaffBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelStaffBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelStaffBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingtable;
    private javax.swing.JButton checkinbtn;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel hotelstaffbooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadtabledetails;
    // End of variables declaration//GEN-END:variables
    
     public class Database {
    public static Connection connect() {
        Connection cn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection(
                    "jdbc:mysql://localhost/staycation", // your database
                    "root", // username
                    ""      // password
            );
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return cn;
    }
   }

    
    
    private void checkin() {
       int row = bookingtable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a booking first!");
        return;
    }

    int reservationId = (int) bookingtable.getValueAt(row, 0);

    try (Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/staycation", "root", "")) {
        String query = "UPDATE reservations SET status = 'Checked In' WHERE reservation_id = ?";
        PreparedStatement ps = cn.prepareStatement(query);
        ps.setInt(1, reservationId);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Guest checked in successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Check-in failed: " + e.getMessage());
    }
    }

    private void checkout() {
        int row = bookingtable.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a booking first!");
        return;
    }

    int reservationId = (int) bookingtable.getValueAt(row, 0);

    try (Connection cn = Database.connect()) {
        String query = "UPDATE reservations SET status = 'Checked Out' WHERE reservation_id = ?";
        PreparedStatement ps = cn.prepareStatement(query);
        ps.setInt(1, reservationId);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Guest checked out successfully!");
        loadbookings(); // refresh table
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Check-out failed: " + e.getMessage());
    }
    }

    private void loadbookings() {
    DefaultTableModel model = (DefaultTableModel) bookingtable.getModel();
    model.setRowCount(0); // clear table

    try (Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/staycation", "root", "")) {
        String query = "SELECT r.reservation_id, u.name, rm.room_type, r.check_in, r.check_out, r.total_cost " +
                       "FROM reservations r " +
                       "JOIN users u ON r.customer_id = u.user_id " +
                       "JOIN rooms rm ON r.room_id = rm.room_id";
        PreparedStatement ps = cn.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("reservation_id"),
                rs.getString("name"),
                rs.getString("room_type"),
                rs.getDate("check_in"),
                rs.getDate("check_out"),
                rs.getDouble("total_cost")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading bookings: " + e.getMessage());
    }
 
        }
    }





