/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staycation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 * 
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    private final char defaultEchoChar;

    public LoginFrame() {
        initComponents();
        defaultEchoChar = showpassword.getEchoChar();
        setupShowPassword();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginsubmit = new javax.swing.JButton();
        loginid = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        showpassword = new javax.swing.JPasswordField();
        showpasswordpl = new javax.swing.JCheckBox();
        clear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO SERENA HOTEL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, -40, 450, 140);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 55, 17);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 69, 17);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 70, 17);

        loginsubmit.setBackground(new java.awt.Color(0, 0, 0));
        loginsubmit.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        loginsubmit.setForeground(new java.awt.Color(255, 255, 255));
        loginsubmit.setText("LOGIN");
        loginsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(loginsubmit);
        loginsubmit.setBounds(350, 320, 110, 30);

        loginid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginidActionPerformed(evt);
            }
        });
        getContentPane().add(loginid);
        loginid.setBounds(180, 100, 240, 22);
        getContentPane().add(username);
        username.setBounds(180, 170, 240, 22);

        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(showpassword);
        showpassword.setBounds(180, 230, 240, 22);

        showpasswordpl.setText("Show password");
        showpasswordpl.setOpaque(true);
        showpasswordpl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpasswordplMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showpasswordplMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showpasswordplMousePressed(evt);
            }
        });
        showpasswordpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordplActionPerformed(evt);
            }
        });
        getContentPane().add(showpasswordpl);
        showpasswordpl.setBounds(420, 230, 110, 20);

        clear.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(220, 320, 90, 24);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vicodec\\Downloads\\Lake Kivu Serena Hotel is located just 3 km from….jpeg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -50, 710, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginidActionPerformed

    private void loginsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginsubmitActionPerformed
        // TODO add your handling code here:
         getlogin();
    }//GEN-LAST:event_loginsubmitActionPerformed

    private void showpasswordplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordplMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordplMouseClicked

    private void showpasswordplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordplActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_showpasswordplActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordActionPerformed

    private void showpasswordplMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordplMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordplMousePressed

    private void showpasswordplMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordplMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordplMouseEntered

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
     getclear();

    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField loginid;
    private javax.swing.JButton loginsubmit;
    private javax.swing.JPasswordField showpassword;
    private javax.swing.JCheckBox showpasswordpl;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

   private void getlogin() {  /*here we get login */
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/staycation", "root", null);
        PreparedStatement pst = cn.prepareStatement(
            "SELECT * FROM login WHERE username=? AND login_id=? AND password=?"
        );
        pst.setString(1, username.getText().trim());
        pst.setString(2, loginid.getText().trim());
        pst.setString(3, String.valueOf(showpassword.getPassword()));
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Login successful");
            new StaycationDB().setVisible(true);  
            dispose(); // Closes the window
        } else {
            JOptionPane.showMessageDialog(null, "Login failed. Access denied");
            
        }
    } catch (SQLException ex) {
        System.getLogger(LoginFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
}

  
     private void setupShowPassword() {
    showpasswordpl.addActionListener(e -> {
        if (showpasswordpl.isSelected()) {
            showpassword.setEchoChar((char) 0); //this  show characters
        } else {
            showpassword.setEchoChar(defaultEchoChar); // restores the original
        }
    });
}

    private void getclear() {
     loginid.setText("");
    username.setText("");
    showpassword.setText("");
    showpasswordpl.setSelected(false);
    showpassword.setEchoChar(defaultEchoChar);

    }      


     private static class StaycationDB extends javax.swing.JFrame {
    public StaycationDB() {
       new StaycationDB().setVisible(true);
    }
}}

    

