/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package staycation;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;



public class RegistrationForm extends javax.swing.JFrame {
   private char defaultEchoChar;


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());
  
    
    public RegistrationForm() {
        initComponents();
       defaultEchoChar = passwordreg.getEchoChar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        registerusers = new javax.swing.JButton();
        clearusers = new javax.swing.JButton();
        backtologin = new javax.swing.JButton();
        passwordreg = new javax.swing.JPasswordField();
        confirmpassword = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        usertype = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Registration");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, -10, 220, 120);

        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 50, 16);

        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 50, 16);

        jLabel4.setText("Phone");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 210, 60, 16);

        jLabel5.setText("User Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 260, 80, 16);

        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 300, 80, 16);

        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(6, 353, 110, 16);

        registerusers.setText("Register");
        registerusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerusersActionPerformed(evt);
            }
        });
        jPanel1.add(registerusers);
        registerusers.setBounds(10, 430, 90, 23);

        clearusers.setText("Clear");
        clearusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearusersActionPerformed(evt);
            }
        });
        jPanel1.add(clearusers);
        clearusers.setBounds(220, 430, 85, 23);

        backtologin.setText("Back to login");
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });
        jPanel1.add(backtologin);
        backtologin.setBounds(430, 430, 99, 23);

        passwordreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordregActionPerformed(evt);
            }
        });
        jPanel1.add(passwordreg);
        passwordreg.setBounds(220, 300, 85, 22);

        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(confirmpassword);
        confirmpassword.setBounds(221, 350, 85, 22);
        jPanel1.add(name);
        name.setBounds(220, 100, 85, 22);
        jPanel1.add(email);
        email.setBounds(220, 150, 85, 22);

        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });
        jPanel1.add(phonenumber);
        phonenumber.setBounds(220, 200, 85, 22);

        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer", "Staff", " " }));
        usertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertypeActionPerformed(evt);
            }
        });
        jPanel1.add(usertype);
        usertype.setBounds(220, 250, 86, 22);

        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(220, 370, 110, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vicodec\\Downloads\\Daftar Biru Sekarang, Biru, Daftar, Sekarang PNG dan Vektor dengan Background Transparan untuk Unduh Gratis.jpeg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 60, 360, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vicodec\\Downloads\\download (2).jpeg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-10, 10, 750, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void registerusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerusersActionPerformed
       getregisteruser();
    }//GEN-LAST:event_registerusersActionPerformed

    private void clearusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearusersActionPerformed
        // TODO add your handling code here:
        getclearuser();
    }//GEN-LAST:event_clearusersActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
        // TODO add your handling code here:
        backtologin();
    }//GEN-LAST:event_backtologinActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
         if (jCheckBox1.isSelected()) {
        passwordreg.setEchoChar((char)0); // this here shows password
        confirmpassword.setEchoChar((char)0); // this here show confirm password
    } else {
        passwordreg.setEchoChar(defaultEchoChar); // this hides the password
        confirmpassword.setEchoChar(defaultEchoChar);
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void passwordregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordregActionPerformed

    private void usertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtologin;
    private javax.swing.JButton clearusers;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField passwordreg;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JButton registerusers;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables

    private void backtologin() {
        new LoginFrame().setVisible(true);
        dispose();
    }

    private void getclearuser() {
         name.setText("");
    email.setText("");
    phonenumber.setText("");
    passwordreg.setText("");
    confirmpassword.setText("");
    usertype.setSelectedIndex(0);
    }

    private void getregisteruser() {
        try {  /*here we connect our database in mysql with netbeans java*/
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/staycation","root",null);

        // Insert into users table
        PreparedStatement pst1 = cn.prepareStatement(
            "INSERT INTO users(name, email, phone, user_type) VALUES(?,?,?,?)"
        );
        pst1.setString(1, name.getText().trim());
        pst1.setString(2, email.getText().trim());
        pst1.setString(3, phonenumber.getText().trim());
        pst1.setString(4, (String) usertype.getSelectedItem());
        pst1.executeUpdate();

        // Insert into login table
        PreparedStatement pst2 = cn.prepareStatement(
            "INSERT INTO login(username, password) VALUES(?,?)"
        );
        pst2.setString(1, email.getText().trim());
        pst2.setString(2, String.valueOf(passwordreg.getPassword()));
        pst2.executeUpdate();

        JOptionPane.showMessageDialog(null, "the Registration was Successful!");
        getclearuser();

    } catch (SQLException ex) {
     java.util.logging.Logger.getLogger(RegistrationForm.class.getName())
    .log(java.util.logging.Level.SEVERE, "Exp occurred", ex);
        JOptionPane.showMessageDialog(null, "Error Message includes: "+ex.getMessage());
    }}}

  

